# Generated by Django 5.1.3 on 2024-11-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
