# Generated by Django 5.1.3 on 2024-11-11 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_member_email_member_password_foodpost_foodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
