# Generated by Django 5.1.3 on 2024-11-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foodpost_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_posts/'),
        ),
    ]
