# Generated by Django 5.1.3 on 2024-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_member_role_remove_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='collection_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
