# Generated by Django 5.1.3 on 2024-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodpost_collection_point_foodpost_whatsapp_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='posted_at',
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='collection_point',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='whatsapp_link',
            field=models.CharField(max_length=255),
        ),
    ]
