# Generated by Django 5.1.3 on 2024-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_foodpost_posted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='collection_point',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
