# Generated by Django 5.1.3 on 2024-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_foodpost_collection_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='whatsapp_link',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
