# Generated by Django 5.1.3 on 2024-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_foodpost_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='requested_by_members',
            field=models.ManyToManyField(related_name='requested_posts', through='main.FoodRequest', to='main.member'),
        ),
    ]
