# Generated by Django 5.1.3 on 2024-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_foodpost_requested_by_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='whatsapp_link',
            field=models.CharField(max_length=15),
        ),
    ]
