# Generated by Django 5.1.3 on 2024-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_foodpost_whatsapp_link_foodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
