# Generated by Django 5.1.3 on 2024-11-14 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_foodrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='quantity_requested',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='title',
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='food_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodpost'),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
    ]
