# Generated by Django 5.1.3 on 2024-11-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_foodrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='requested_by_members',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='requested_by',
        ),
    ]
