# Generated by Django 5.1.3 on 2024-11-14 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_foodpost_requested_by_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
    ]
